Repository depromeet/ohmebddeng-backend, pull requests merged in 2021-12, with the labels that each got.

#92 Fix: 🐛 이미지가 null인 경우를 제외한 데이터만 가져옴
  src/food/food.service.ts
Labels: bug🐞

#81 Refactor #75 food API Error Handling 추가
  nest-cli.json
  src/common/enums/error-message.ts
  src/food/dto/find-food.dto.ts
  src/food/food.controller.ts
  src/food/food.service.ts
  src/user/dto/find-user-level.dto.ts
Labels: Refactor 🛠

#89 Refactor #78 User Module에 에러 핸들링 적용
  src/user/dto/create-user-level.dto.ts
  src/user/dto/find-user.dto.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
  src/user/utils/evaluate-user-level.ts
Labels: Refactor 🛠

#96 Feat #90 태그 추가 및 개수 제한
  src/common/enums/taste-tag.ts
  src/review/review.controller.ts
  src/review/review.service.ts
  src/review/utils/produceTasteTag.ts
Labels: Feature Develop ⌨️

#83 Refactor #82 review API error handling 추가
  .eslintrc.js
  src/common/enums/taste-tag.ts
  src/food/food.controller.ts
  src/review/review.controller.ts
  src/review/review.service.ts
  src/review/utils/produceTasteTag.ts
Labels: Refactor 🛠
