Repository depromeet/ohmebddeng-backend, pull requests merged in 2021-11, with the labels that each got.

#67 Fix #66 TasteTag가 DB에 적용되지 않는 문제 해결
  src/review/dto/create-review.dto.ts
  src/review/dto/create-reviews.dto.ts
  src/review/review.service.ts
  src/review/utils/produceTasteTag.ts
Labels: bug🐞

#72 refactor: 💡 매운 음식 추천 탭에서 사용자 레벨에 해당하는 음식만 추천 해주도록 수정
  src/food/food.controller.ts
  src/food/food.module.ts
  src/food/food.service.ts
Labels: Refactor 🛠

#74 Feat #73 slack webhook 추가
  .gitignore
  package-lock.json
  package.json
  src/app.module.ts
  src/common/filters/http-exception.filter.ts
Labels: Feature Develop ⌨️

#80 Refactor #79 path alias 도입
  package-lock.json
  package.json
  src/food/food.controller.ts
  src/food/food.service.ts
  tsconfig.json
Labels: Refactor 🛠

#86 Refactor #84 음식 로고와 관련된 이미지 칼럼 추가 및 음식 리뷰 API 수정
  src/food/dto/find-food.dto.ts
  src/food/entities/food.entity.ts
  src/food/food.controller.ts
  src/food/food.service.ts
Labels: Refactor 🛠

#88 Refactor #87 User Controller에서 swagger 코드를 제거하고, nest-cli가 자동생성하게 합니다
  nest-cli.json
  src/user/dto/find-user.dto.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: Refactor 🛠
